name: flutter_application_29
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.0.7
  
  
  camera: ^0.11.2
  
  
  uuid: ^4.5.1
  
  synchronized: ^3.3.1
  video_compress: ^3.1.4
  
  geolocator: ^12.0.0
  http_parser: ^4.1.2
  device_info_plus: ^11.5.0
  videosdk: ^2.3.1
  

  flutter_local_notifications: ^19.3.0
  workmanager: ^0.8.0
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  animate_do: ^4.2.0
  flutter_spinkit: ^5.2.1
  glassmorphism: ^3.0.0
  mime: ^2.0.0
 
  flutter_secure_storage: ^9.2.4
  flutter_animate: ^4.5.0
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.11.0
  record: ^6.0.0
  
  chewie: ^1.11.3
  hive_flutter: ^1.1.0
  encrypt: ^5.0.3
  file_picker: ^10.1.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  fl_chart: ^1.0.0
  audioplayers: ^6.4.0
  bubble: ^1.2.1
  url_launcher: ^6.3.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  image: ^4.5.4
  hive: ^2.2.3
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  video_player: ^2.10.0

  
  
  
  platform: ^3.1.6
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/fonts/
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Icon-512 (1).png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/Icon-512 (1).png"